name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, 1.82.0]

    steps:
      - uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy
          toolchain: ${{ matrix.rust }}

      - name: Check Formatting
        run: |
          cd squeezenet-burn
          cargo fmt --all -- --check

      - name: Run Clippy
        run: |
          cd squeezenet-burn
          cargo clippy -- -D warnings

      - name: Build
        run: |
          cd squeezenet-burn
          cargo build --verbose

      - name: Run tests
        run: |
          cd squeezenet-burn
          cargo test --verbose
